language: python
python:
  - "2.6"
  - "2.7"

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y

env:
  - DJANGO=1.4
  - DJANGO=1.5

install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install . --use-mirrors

before_script: rethinkdb --daemon

script: python tests/tests.py
