language: python
python:
  - "2.6"

before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y

env:
  - TOXENV=py26-1.4,py26-1.5
  - TOXENV=py27-1.4,py27-1.5
  - TOXENV=pypy-1.5

install:
  - pip install tox
  - pip install . --use-mirrors

before_script: rethinkdb --daemon

script: tox

